os: linux
dist: bionic
arch: amd64
language: generic
#workaround for travis-ci bugs
filter_secrets: false

jobs:
  include:
  - stage: Build
    name: "AMD64 build test"
    arch: amd64
    services: docker
    before_script:
      - git clone https://github.com/binrats/gtirb
      - git clone https://github.com/binrats/gtirb-pprinter
      - docker pull binrats/ddisasm-base
      - docker run -d -t --name binrattester -w /ddisasm --mount src="$(pwd)",target=/ddisasm,type=bind binrats/ddisasm-base /bin/sh
    script:
      - docker exec binrattester /bin/sh -c "cd /ddisasm/gtirb && git checkout -b d3 D3.0 && cmake . -Bbuild && cd build && make install -j2"
      - docker exec binrattester /bin/sh -c "cd /ddisasm/gtirb-pprinter && cmake . -Bbuild && cd build && make install -j2"
      - docker exec binrattester /bin/sh -c "cd /ddisasm && cmake -DLIEF_ROOT=/usr . -Bbuild && cd build && make install -j2"
        # Now register the new libraries so they are usable
      - docker exec binrattester /bin/sh -c "ldconfig"
      - docker exec binrattester /bin/sh -c "cd /ddisasm/examples/ex1 && make && ddisasm --dwarf ex"
    after_script: docker container stop binrattester
  - stage: Build
    name: "ARM64 build test"
    arch: arm64
    # Needed to work around travis-ci bugs that freeze output, then timeout
    services: docker
    before_script:
      - git clone https://github.com/binrats/gtirb
      - git clone https://github.com/binrats/gtirb-pprinter
      - docker pull binrats/ddisasm-base
      - docker run -d -t --name binrattester -w /ddisasm --mount src="$(pwd)",target=/ddisasm,type=bind binrats/ddisasm-base /bin/sh
    script:
      - docker exec binrattester /bin/sh -c "cd /ddisasm/gtirb && git checkout -b d3 D3.0 && cmake . -Bbuild && cd build && make install -j2"
      - docker exec binrattester /bin/sh -c "cd /ddisasm/gtirb-pprinter && cmake . -Bbuild && cd build && make install -j2"
      - docker exec binrattester /bin/sh -c "cd /ddisasm && cmake -DLIEF_ROOT=/usr . -Bbuild && cd build && make install -j2"
        # Now register the new libraries so they are usable
      - docker exec binrattester /bin/sh -c "ldconfig"
        # travis_wait is required as compiling the souffle cpp can take more than the 10 minute travis timeout
      - travis_wait 40 sleep 40m & docker exec binrattester /bin/sh -c "cd /ddisasm/examples/ex1 && make && ddisasm --dwarf ex"
    after_script: docker container stop binrattester
