os: linux
dist: bionic
arch: arm64

jobs:
  include:
  - stage: Build
    name: "Build dependencies"
    services: docker
    before_script:
      - docker pull binrats/ddisasm-base
      - git clone https://github.com/binrats/gtirb
      - git clone https://github.com/binrats/gtirb-pprinter
    script:
      - docker run -w /ddisasm --mount src="$(pwd)",target=/ddisasm,type=bind binrats/ddisasm-base .ci/travis.sh
